### ISSUE TITLE
Not comparing Minecraft versions accurately

### ISSUE THREAD

**Issue by Roflicide** [MinecraftServerControl/mscs#122] opened 2016-03-03 22:31 UTC
I've updated my server to 1.9. In MSCS there is a part of the script that decides what to display when I run the `map` command (both before and after I run it). Here's one of those parts so you know what I'm talking about:
````
    if [ $(compareMinecraftVersions $(getServerVersion $1) 1.7) -ge 0 ]; then
        sendCommand $WORLD 'tellraw @a {
          "text" : "",
          "extra" : [
            {
              "text" : "[Server] Mapping is complete. You can access the maps "
            },
            {
              "text" : "here",
              "color" : "aqua",
              "clickEvent" : {
                "action" : "open_url",
                "value" : "'$MAPS_URL'/'$WORLD'"
              }
            },
            {
              "text" : "."
            }
          ]
        }'
    else
        sendCommand $1 "say Mapping is complete.  You can access the maps at:"
        sendCommand $1 "say $MAPS_URL/$WORLD"
    fi
  fi
````

For some reason, it's not going to the first `if` block and instead is going to the `else` block (I tested this by printing out something in the `else` block and it indeed printed) even though it should since the server is greater than 1.7.

I think this might be an issue with how it's checking versions--perhaps something changed? (Relevant Issue [#117](https://github.com/MinecraftServerControl/mscs/issues/117)

**Comment by zanix** [comment] 2016-03-04 00:11
This block only compares the version so it can use the enhanced say command found in versions 1.7 and higher

**Comment by sandain** [comment] 2016-03-08 05:27
This is a duplicate of #117. The versions.json file at the old location does not have a version 1.9, so there is no time value for the algorithm to work with.  The new location has 1.9, so simply updating the url should fix this.  However, my perl regex that handles the file may no longer be sophisticated enough, and may need some work.  I'll take a closer look at this tomorrow.

**Comment by zanix** [comment] 2016-03-08 05:32
I just downloaded the old `versions.json` and it does have a listing for 1.9

**Comment by sandain** [comment] 2016-03-08 05:34
Huh, I must have looked at a cached copy.  You are right, 1.9 is listed in the old location

**Comment by sandain** [comment] 2016-03-08 05:36
I wonder what the issue is, and if it happens on my servers.  Again, I'll take a closer look tomorrow.

**Comment by sandain** [comment] 2016-03-09 05:01
I don't have a fix yet, but I can confirm that it is not working for me either.  I'll take a closer look at the code that does this over the next couple of days and come up with a fix.

**Comment by sandain** [comment] 2016-03-12 00:22
The code was failing because version 1.7 is not listed in the file.  I assume it used to be, because this code used to work.  Anyway, the fix was just changing the version compared to 1.7.2 with commit b02423dbe814cb866cffddf7dbc0efe51e72ca9d.

**Closed by sandain** 2016-03-12 00:22 UTC
