### ISSUE TITLE
Store Backups on Cloud Storage

### ISSUE THREAD

**Issue by nprail** [MinecraftServerControl/mscs#154] opened 2017-01-18 19:56 UTC
A nice feature would be the ability to store backups on cloud storage such as AWS S3, Google Cloud Storage, or Azure Cloud Storage. Backups aren't terribly useful if your whole machine goes down and the backups were stored locally.

**Comment by sandain** [comment] 2017-01-18 20:28
I have not tested this, but it seems that you should be able to set the `mscs-backup-location` variable in the `mscs.properties` to point to your cloud storage.  The default key/value for this variable is `mscs-backup-location=/opt/mscs/backups`, but according to the rdiff-backup docs this could look like `[[[user@]host.foo]::destination_directory`, so something like `mscs-backup-location=nprail@awsserver.com::mscs_backups` might do the trick without any modification to the script.

If you test this and it works, it might be nice to add this kind of information into either the wiki or README.

**Comment by sandain** [comment] 2017-01-18 20:45
Well, the script has a [check](https://github.com/MinecraftServerControl/mscs/blob/master/msctl#L1134) that will make the above fail.  We should probably remove that check and add `--create-full-path` to the `rdiff-backup` command instead.

**Comment by nprail** [comment] 2017-01-18 20:46
According to [this](http://old.blog.phusion.nl/2013/11/11/duplicity-s3-easy-cheap-encrypted-automated-full-disk-backups-for-your-servers/) article, `rdiff-backup` does not work with AWS S3 because it requires `rdiff-backup` to be installed on the remote machine as well. But the article talks about another tool called Duplicity that works with S3. Duplicity is similar to `rdiff-backup` and written by the same person. I'm going to make a fork and try to switch to Duplicity and see if it works better.

**Comment by sandain** [comment] 2017-01-18 20:53
Interesting, my work box already has `duplicity` installed.  Ubuntu appears to install `duplicity` when the `ubuntu-desktop` package is installed, I wonder if the same can be said for the `ubuntu-server` package.

**Comment by nprail** [comment] 2017-01-18 20:55
It was not pre-installed on my server. I just installed it.

**Comment by sandain** [comment] 2017-01-23 17:19
I found [this script](https://gist.github.com/MartinNowak/753e29f86eb6543e2269637081212e70) that converts from `rdiff-backup` to `duplicity`.  If we do a full swap, we will need to add a script like this to the `update.d` directory as well.

**Comment by zanix** [comment] 2017-01-23 18:28
I checked for `duplicity` on my server and I would have to install it so it seems it does not come with the `ubuntu-server` package.

This script looks like it only restores the latest backup and converts it to duplicity so therefor you would loose all your older backups. Maybe there is a way around this?

I do like that it still supports backup to  a local directory, using something like `file:///usr/local/backup` as the destination.

It looks like you can specify full vs incremental backups. It looks like `duplicity` returns an error if a full backup does not exist. This either needs to be handled or maybe an additional command to run a full backup on demand?

I have some more reading to do on the docs page, but this does look good so far.

**Comment by sandain** [comment] 2017-01-24 18:42
I was going to go ahead and submit an interim patch that uses `rdiff-backup` to take care of the directory creation as mentioned in my second comment above, but I need to give the patch some more thought -- my initial attempt failed.

[Line 1148](https://github.com/MinecraftServerControl/mscs/blob/master/msctl#L1148):
```
if ! $RDIFF_BACKUP -v5 --print-statistics $EXCLUDE_OPTION "$WORLDS_LOCATION/$1" "$BACKUP_LOCATION/$1" >> "$BACKUP_LOG"; then
```
The `rdiff-backup` command all by itself works just fine, it creates the directory as expected.  The problem is that the output is being piped to `$BACKUP_LOG` which by default is in the backup directory that does not exist yet.  We will either need to write to a temporary file and concatenate later or change the location of the log file.

**Comment by sandain** [comment] 2017-01-24 19:03
I just read through the `rdiff-backup` man page and realized that log files are automatically written to `$BACKUP_LOCATION/<world>/rdiff-backup-data/backup.log` for backup sessions and `$BACKUP_LOCATION/<world>/rdiff-backup-data/restore.log` for restore sessions.  If we want to retain the `$BACKUP_LOG` as-is, we can probably drop the pipe command, add `--terminal-verbosity 0`, and do something like `cat $BACKUP_LOCATION/<world>/rdiff-backup-data/backup.log >> $BACKUP_LOG`.

**Comment by zanix** [comment] 2017-01-24 19:15
When I originally added the `rdiff-backup` code, I added the log because I didn't think it did otherwise. I think dropping the log may be a good idea.

I also noticed my log is quite large (157Mb), I wonder if we should start using the log rotate function on it if we keep it.

**Comment by sandain** [comment] 2017-01-24 19:38
I can't figure it out from the man page, but hopefully `duplicity` automatically creates the target directory since it doesn't seem to have anything similar to the `--create-full-path` option. It does however have a `--log-file` option that we could use with `$BACKUP_LOG`.

**Comment by nprail** [comment] 2017-01-25 13:42
I'm currently working on switching the script to `duplicity`. Since I have school and work to do alongside this as well as the fact that I'm not super adept at Bash, it may take me a while to finish. Maybe 2 weeks.

**Comment by sandain** [comment] 2017-02-21 19:07
I took a stab at this, and it became complicated by the fact that `duplicity`, by default, wants to encrypt the archive.  This requires that the user setup a GPG key.  I made a limited attempt to script an automatic key generation, but I couldn't get it to work due to some kind of permission issue. There is the `--no-encryption` option that could be explored, but it seems like encryption might not be such a bad thing.

Maybe the solution is to default to using the `--no-encryption` option for `duplicity` if we can't detect that a GPG key is installed (defaults to being installed at `~/.gnupg/secring.gpg`).

**Comment by nprail** [comment] 2017-02-23 14:38
Encryption is nice but the only problem is that if you lose you GPG key, those backups are useless. I don't think that it should be GPG encrypted by default. For example, if the key is auto-generated, it stays on the machine that you are backing up. If the machine has a data loss (which is why you are backing up in the first place), that GPG key is gone. Your backups are useless without cracking the encryption. (Which I hear is nearly impossible) 

But I do think there should be an option to encrypt backups. Just not by default. Or at least make it super clear that you need to backup you GPG key somewhere safe. 

By the way, I haven't gotten anywhere on my version of the switch to `duplicity`. I really don't know `bash` well enough to attempt this sort of thing.

**Comment by zanix** [comment] 2017-02-23 16:41
You can write out how you would run the commands manually and any additional steps you make like checking for specific things.

**Comment by Roflicide** [comment] 2021-04-25 02:25
Hi,

I know this is a pretty old issue, but there's actually a pretty simple solution for this that I came across when I took some cloud training recently. As far as I'm aware, all of the major cloud providers have a command line utility for cloud storage that will allow you to sync the local directory with the remote cloud storage.

With GCP (Google Cloud Platform), you can use the `gsutil` tool, specifically the [`gsutil rsync` command](https://cloud.google.com/storage/docs/gsutil/commands/rsync#change-detection-algorithm):

```
gsutil rsync /opt/mscs/backups/myWorld gs://mybucket/myWorldBackup
```
This will sync the `/opt/mscs/backups/myWorld` folder on your local machine to  the `myWorldBackup` folder in your GCP bucket (named `mybucket`). You could run this command periodically using `cron` so the backups stay in-sync with the cloud storage. You could also use bucket [Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) features to automatically delete files/folders in your bucket after a certain number of days, or add the `-d` flag to the command above to automatically delete any files/folders in your bucket that are not in the local folder.

I'm not sure about the other cloud providers (i.e. Amazon AWS or Microsoft Azure), but I have to imagine they have something similar.

**Comment by sandain** [comment] 2021-04-26 17:01
I use [rclone](https://rclone.org/) for this purpose. It makes copying files to and from cloud storage (any vendor) easy.

I think it is time we close this issue.  This is not really in scope for MSCS.

**Closed by sandain** 2021-04-26 17:01 UTC
Labels: enhancement
