### ISSUE TITLE
couldn't retrieve the server's process ID

### ISSUE THREAD

**Issue by 101van** [MinecraftServerControl/mscs#251] opened 2020-06-20 05:25 UTC
after doing mscs start Survival (the world name) it gave me the error message "couldn't retrieve the server's process ID." how do i fix this

**Comment by sandain** [comment] 2020-06-22 17:30
Hi @101van. Could you please post your `mscs.defaults` file, and the `mscs.properties` file for your Survival world? We need more information to understand what is going on with your issue.

**Comment by sandain** [comment] 2020-08-03 18:00
@101van: Hopefully you were able to figure out the issue here.  I'm going to close this issue. Feel free to reopen it if needed.

**Closed by sandain** 2020-08-03 18:00 UTC

**Comment by just2close** [comment] 2021-10-03 11:24
Hi sandain,

got the same problem:
Error starting the server: couldn't retrieve the server's process ID.
[mscs.defaults.txt](https://github.com/MinecraftServerControl/mscs/files/7273219/mscs.defaults.txt)

mscs.properties only says: mscs-enabled=true

**Comment by sandain** [comment] 2021-10-03 15:10
Hi @just2close. Please open a new issue and post your `console.out` file.  I'm sure it will tell us what the issue is.
